### ISSUE TITLE
Weitere Daten

### ISSUE THREAD

**Issue by jonathanschiefer** [MichaelKreil/twitter-analysis#2]
Hi Michael,

vielen Dank für das bereitstellen der Daten, ich habe mir die Daten ein bisschen angeschaut und habe jetzt ich Idee im Kopf, die ich gerne ausprobieren möchte. Ich komme eigentlich aus der Datenanalyse von Hirndaten  und wollte testen, ob man Methoden von dort auch auf twitter Daten anwenden kann. Allerdings bräuchte ich dafür mehr Daten (im speziellen die Zeitpunkte der tweets, im einem zweiten Schritt evtl die Texte der tweets, aber nicht notwendigerweise von allen Nutzern) und wollte fragen, ob die diese Daten hast und mir irgendwie zur Verfügung stellen könntest?

Viele Grüße,
Jonathan

**Comment by MichaelKreil** [comment]
Hi Jonathan,
Kann ich dir im Prinzip liefern ... aber leider kann ich keinen Full-Dump machen, weil die Datenmenge zu groß wäre. Ich könnte dir aber alle Tweets zu einem Hashtag, oder alle Tweets einer Gruppe geben.
Kannst du mir mehr dazu sagen?

**Comment by jonathanschiefer** [comment]
Hi Michael,
also fürs erste wären die Zeitpunkte der Tweets das wichtigste (das ist die l_tweets_created_at Datei, da sind bisher max 200 Tweets pro User drin). Da bräuchte ich so viele wie möglich. Wär das auch schon so groß? Notfalls könnte ich dir auch einen Datenträger zukommen lassen, falls das hilft.. 
Die Texte der Tweets wären dann erst in einem zweiten Schritt (vorausgesetzt Schritt 1 funktioniert) notwendig.

**Comment by MichaelKreil** [comment]
Ok, also, zahlreiche Accounts gibt es inzwischen nicht mehr. Inzwischen sind wiederum andere dazugekommen. Das ganze Ding wieder auf die Füße zu stellen und so große Datenmengen abzurufen überschreitet gerade meine zeitlichen Möglichkeiten. Sorry :/
